g.setFontCustom(atob("AAAAAAAAAAAAAAAAAAAAAAAAH/zA/+YAAAAAAAHwAA4AAAAAA+AAHAAAAAAAAQACDAAYbADP4B/8A/zAGYZADH4A/+A/7AHYYADCAAAAAAAQAeHgH4eBzgwMMHnhw88GGBw4wHj+AcPgAAAAAAAAAAB4AA/gAGMGAwhwGMYAfuABzgABzgAc+AOMYBhBAAMYAB/AAHwAAAAAHwD5+A/8YGPDAw8YGPzA/HYD4fAADwAB/AAOYAABAAAAHwAA4AAAAAAAAAAP/AH/+D4B84AB2AAGAAAAAAAwAA3gAOPAPg//wB/4AAAAEAABiAAGwAA8AA/AAH+AAGwAByAAEAAAAAAAMAABgAAMAABgAH/wA/+AAMAABgAAMAABgAAAAAAAIAAfAADwAAAABgAAMAABgAAMAABgAAAAAAAAAAAAADAAAYAAAAAAAAAAAAAAAADgAB8AB+AA+AA+AA/AAHAAAAAAAAAAAAAAAAAP/gD/+A4A4GADAwAYGADA4A4D/+AP/gAAAAAAAAAAAAAABgAAMAADAAA//4H//AAAAAAAAAAAAAAAOA4DwPA4D4GA7AwOYGDjA44YD+DAPgYAAAAAAABgMAcBwHAHAwwYGGDAwwYHPHAf/wB58AAAAAAAAAPAAD4AB7AA8YAPDAHgYA//4H//AADAAAAAAAAH+MA/xwGMDAxgYGMDAxwYGHPAwfwAA4AAAAAAAAD/gB/+Aew4HMDAxgYGMDAxw4AH+AAfgAAAAAAAGAAAwAAGADAwB4GB+Aw+AGfAA/gAHwAAAAAAAAAPPgD/+A544GGDAwwYGGDA544D/+APPgAAAAAAAB+AAf4AHDjAwMYGBjAwM4HDOAf/gB/wAAAAAAAADAYAYDAAAAAAAAAAAAAAYDAfAYHwAAAAAAAAIAADgAAcAAHwAA2AAO4ABjAAMcADBgAAAAAAAAMwABmAAMwABmAAMwABmAAMwABmAAEQAAAAAAAADBgAccABjAAO4AA2AAGwAAcAADgAAIAAAAAAAABgAAcAAHAAAwOYGDzAw4AH+AAfgAAwAAAAAAAAAAGAAP/AH5+BwAwcADDB+Mw/5mHDMxgZmMDMxnxmP/Mw4YDABAcAYB4OAD/gABgAAAAAAAAAAYAAfAAPwAPwAH2AH4wA8GAH4wAP2AAPwAAfwAAfAAAYAAAAAAAH//A//4GGDAwwYGGDAwwYGGDA544D/+APPgAAAAAAAADAAH/AD/+AcBwHADAwAYGADAwAYGADA4A4DweAODgAAAAAAAH//A//4GADAwAYGADAwAYGADAYAwD4+AP/gAfwAAAAAAAAAAAH//A//4GGDAwwYGGDAwwYGGDAwwYGADAwAYAAAAAAAH//A//4GGAAwwAGGAAwwAGGAAwAAGAAAAAAAAAAH/AD/8AcBwHAHAwAYGADAwYYGDDA4YYDz/AOfwAAAAAAAH//A//4ADAAAYAADAAAYAADAAAYAADAA//4H//AAAAAAAAAAAH//A//4AAAAAAAAAAAADAAAeAAA4AADAAAYAADAAAYAAHA//wH/8AAAAAAAA//4H//AA4AAPAAD8AA7wAOHADgcA4B4GAHAgAYAAAAAAAH//A//4AADAAAYAADAAAYAADAAAYAADAAAAAAAA//4H//A+AAB8AAD4AAH4AAPwAAfAAPwAH4AD8AB8AA+AAH//A//4AAAAAAAH//A//4DwAAPgAAeAAB8AADwAAHgAAeA//4H//AAAAAAAAH/AB/8AeDwHAHAwAYGADAwAYGADA4A4DweAP/gA/4AAAAAAAA//4H//AwMAGBgAwMAGBgAwMAGDgA44AD+AAHgAAAAAAAAA/4AP/gDgOA4A4GADAwAYGADAwAYHAHgeD+B/8wD+GAAAAAAAH//A//4GDAAwYAGDAAwcAGDwA4/gD+fAPg4AABAAAAAAAAADAB4eAfhwHOHAwwYGGDAw4YGDDA4c4Dx+AOHgAAAAAAAGAAAwAAGAAAwAAGAAA//4H//AwAAGAAAwAAGAAAwAAAAAAAAAH/4A//wAAPAAAYAADAAAYAADAAAYAAPA//wH/8AAAAAAAAgAAHAAA/AAB/AAD+AAD+AAD4AAfAAfwAfwAfwAH4AA4AAEAAAAAAAAAA+AAH/AAH/gAD/AAD4AD+AH+AH8AA+AAH+AAD+AAD/AAD4AH/AP/AH+AA8AAAAAAAAAGADA4A4HweAPPgA/wAB8AAfwAPvgDweA8B4GADAAAAAAAAwAAHAAA+AAB8AAD4AAH/AA/4AfAAPgAHwAA8AAGAAAAAAAAAAwAYGAPAwD4GB7AweYGPDAzwYH4DA+AYHADAwAYAAAAAAAH//+///2AAGwAAwAAAAAAGAAA+AAD8AAD8AAD4AAH4AAHgAAMAAAAAAAGAAGwAA3//+///wAAAAAAAOAAHwAD4AA8AAD8AADwAAGAAAAAAABgAAMAABgAAMAABgAAMAABgAAMAABgAAAEAAAwAADAAAIAAAAAAAAAAAAAAAAAEeABn4Ad3ADMYAZjADMYAZmAB/4AP/AAAAAAAA//4H//ABgwAYDADAYAYDADg4AP+AA/gABwAAAAAAAAA/gAP+ADg4AYDADAYAYDADAYAOOABxwAAAAAAAAH8AB/wAcHADAYAYDADAYAMGA//4H//AAAAAAAAA/gAP+ADs4AZjADMYAZjADMYAPnAA8wABgAAAAAAAABgAAMAAP/4D//A5gAGMAAxAAAAAAAAAAH8YB/zAcHMDAZgYDMDAZgcHcD//Af/wAAAAAAA//4H//ABgAAYAADAAAYAADgAAf/AB/4AAAAAAAGf/Az/4AAAAAAAAAAMz//mf/4AAAAAAA//4H//AAOAADwAA/AAOeADh4AQDAAAIAAAAAAAH//A//4AAAAAAAAf/AD/4AMAADAAAYAADAAAcAAD/4AP/ABgAAYAADAAAYAADgAAP/AA/4AAAAAAAAf/AD/4AMAADAAAYAADAAAcAAD/4AP/AAAAAAAAA/gAP+ADg4AYDADAYAYDADAYAcHAB/wAH8AAAAAAAAD//gf/8DAYAYDADAYAYDADg4AP+AA/gABwAAAAAAAAAOAAH8AB/wAcHADAYAYDADAYAYDAD//gf/8AAAAAAAD/4Af/ABgAAYAADAAAQAAAAAAAAAB5wAfnADMYAZjADGYAYzADn4AOeAAAAAAAADAAAYAAf/wD//ADAYAYDAAAAAAAAD/gAf+AAA4AADAAAYAADAAAwAf/AD/4AAAAAAAAYAAD4AAP4AAP4AAPAAH4AH4AD8AAcAAAAAAAAADwAAf4AA/4AAPAAP4AH4ADwAAfgAA/gAA/AAB4AH+AD+AAeAAAAAAAAACAYAcHADzwAH8AAfAAH8ADx4AcHACAIAAAAAAAAcAMD4BgP4MAP/AAPwAP4AP4AD4AAcAAAAAAAAADAYAYHADD4AY7ADOYAfjADwYAcDADAYAAAAAAAAAQAAHAA//4P8/jgAOYAAQAAAAAAH//+///wAAAAAACAACcAAx/n+H//AA4AACAAAAAAAAABwAAcAADAAAYAADgAAMAAAwAAGAAAwAAOAADgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),32,atob("BwQGDQ0PDQQHBgoLBAgGCwsLCwsLCwsLCwsFBQsLCwsUDwwODgwLDQ4FDA0LEQ0ODQ4NDQ4NEBMNDg0GCgYICggLDAsLDAkLCwQFCwQSCwwMDAgKCAsLEAsLCwgECA0="), 256+21);



// *
g.clear();
//g.setFontRoboto20();
y=0;
str = `
'' ** (( )) ++ ,, -- .. // 
AA BB CC DD EE FF GG HH II JJ KK 
LL MM NN OO PP QQ RR SS TT UU VV
WW XX YY ZZ
[[ \\ ]] __ ^^ 
aa bb cc dd ee ff gg hh ii jj kk
ll mm nn oo pp qq rr ss tt uu vv
ww xx yy zz
[0123456789]
Waltz, nymph! For quick jigs
vex bug? B00G@@ {_:-/_}
`;
g.drawString(str,0,y); y+= g.getFontHeight();
g.flip();

g.clear();
y=0;
str = `
09:00 - 10:00    This is your first lesson
11:30 - 12:00    Remember it!
02:15 - 03:15    OK, forget it.
`;
g.drawString(str,0,y); y+= g.getFontHeight();
//g.flip();
//*/

