/*
let widths = new Uint8Array([6, 3, 5, 0,0, 9, 0, 3, 5, 5,8,9,4,8,3,7,
    9,5,8,8,8,8,8,8,9,9, 3,0,0,0,0,9,
    0,9,8,8,8,8,8,9,8, 5,8,8,8,9, //M
    9,9,8,8,8,8,7,8,9,11,9,9,8, //Z
    0,0,0,0,0,0,
    8,8,8,8,8,6,9,9,3,6,9,5,9, //m
    8,8,9,9,7,9,6,8,9,9,9,9,8
]);
*/
Graphics.prototype.setFontKnx18 = function (scale) {
this.setFontCustom(atob("AAAAAAAAAAAAAAAAAAP8gAAAAAAMAAAAAMAAAAAAAAGAQJBgGGAAYABhgGCQIBgAAAAAAEAAIAAAAAB+AOBgQAQAAAAAAQAQOBgB+AAAAAAAAIABJAAqAAUAAqABJAAIAAAAAAAAIAAIAAIAB/AAIAAIAAIAAAAAAAAAIAAwAAAAAAAIAAIAAIAAIAAIAAIAAAAAAAAAwAAAAAAABwAGAAIABwAOAAAAAAAAD/AEAgIAQIQQIAQEAgD/AAAAAAACAAEAAP/wAAAAAACBwECQIEQIIQEQQDgQAAAAAACBAEAgIQQIQQEogDHAAAAAAAAHAAZABhAOBAAfwABAAAAAAAPhAIggIgQIgQIQgIPAAAAAAAB/ACQgEgQIgQIQgAPAAAAAAAIAAIAAIBwIOAJwAOAAAAAAAADHAEogIQQIQQIQQEogDHAAAAAAADgAEQAIIQIIQIIgETAD8AAAAAAAAxgAAAAAACAAEAAIAAIMwIQAEgADAAAAAAAAADwA+ADCAMCADCAA+AADwAAAAAAP/wIQQIQQIQQEogDHAAAAAAAD/AEAgIAQIAQEAgCBAAAAAAAP/wIAQIAQIAQEAgD/AAAAAAAP/wIQQIQQIQQIQQIAQAAAAAAP/wIQAIQAIQAIQAIAAAAAAAAD/AEAgIAQIAQIIQEIgAPgAAAAAAP/wAQAAQAAQAAQAAQAP/wAAAAAAIAQP/wIAQAAAAAAABAAAgAAQAAQAAgP/AAAAAAAP/wAQAAoABEACCAMBwAAAAAAP/wAAQAAQAAQAAQAAQAAAAAAP/wGAABgAAYABgAGAAP/wAAAAAAP/wGAABgAAYAAGAABgP/wAAAAAAD/AEAgIAQIAQIAQEAgD/AAAAAAAP/wIIAIIAIIAEQADgAAAAAAAD/AEAgIAQIBQEAgD/QAAAAAAP/wIIAIIAIMAETADgwAAAAAADBAEggIQQIQQEIgCHAAAAAAAIAAIAAP/wIAAIAAAAAAAAP/AAAgAAQAAQAAgP/AAAAAAAOAAB4AAHAAAwAHAB4AOAAAAAAAAPAAA8AADwA8APAAA8AADwA8APAAAAAAAAIAwGDABsAAQABsAGDAIAwAAAAAAIAAGAABgAAfwBgAGAAIAAAAAAAAIBwIGQIIQIQQJgQOAQAAAAAAADAAkgBIQBIQBIQA/gAAAAAAP/gAggBAQBAQAggAfAAAAAAAAfAAggBAQBAQBAQAggAAAAAAAfAAggBAQBAQAggP/gAAAAAAAfAAkgBEQBEQAkQAcgAAAAAABAAH/wJAAIAAAAAAAAAfAAgiBASBASBASAgkA/4AAAAAAP/wAgABAABAABAAAgAAfwAAAAAAF/wAAAAAAAAIAAEAAEE/4AAAAAAP/wAEAAEAAKAARAAggBAQAAAAAAP/AAAgAAQAAAAAAB/wAgABAAA/wBAAAgAAfwAAAAAAB/wAgABAABAAAgAAfwAAAAAAAfAAggBAQBAQAggAfAAAAAAAA/8AggBAQBAQBAQAggAfAAAAAAAAfAAggBAQBAQBAQAggA/8AAAAAAA/wAQAAgABAABAAAAAAAAARAAogBIQBEQBEQAigARAAAAAAABAAH/ABAgBAQAAAAAAB/AAAgAAQAAQAAgB/wAAAAAABwAAMAADAAAwADAAMABwAAAAAAAB+AABwAGAAYAAGAABwB+AAAAAAABgwARAAKAAEAAKAARABgwAAAAAABwEAMEADYAAgADAAMABwAAAAAAABAwBBQBCQBEQBIQBwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"), 32,atob("BgMFAAAJAAMFBQgJBAgDBwkFCAgICAgICQkDAAAAAAkACQgICAgICQgFCAgICQkJCAgICAcICQsJCQgAAAAAAAAICAgICAYJCQMGCQUJCAgJCQcJBggJCQkJCA=="), (scale << 8) | 18);
};