/*
For DigitMaker:
digitStart = [    "0",    "28",    "41",    "66",    "89",    "115",    "141",    "166",    "193",    "218"]
digitEnd = [    "29",    "42",    "65",    "90",    "114",    "140",    "167",    "193",    "217",    "243"]

*/
let WRITE = true;
let offset=0;
let cnt=0;
let filename = "Urbanist40";
let filesize = 5463;
let offstr = "";
let lenstr = "";
let 
digit = atob("HSrE/wAA///ve4IQfe8MY3WtBCH73vOchjH3vQhCjnNxjHnOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAesoAAAAAAAAAAAAAAM5BERG1AAAAAAAAAAADYREREREYUAAAAAAAAAeBEb5V2YERIAAAAAAAB4EbcAAAAFgRIAAAAAADgRIAAAAAAHgR0AAAAACREgAAAAAAAHgUcAAAAHEZAAAAAAAAAMEZAAAACRFwAAAAAAAAAJETAAAHEZAAAAAAAAAABxEgAABRGgAAAAAAAAAACxQAAAsYAAAAAAAAAAAA0RoAAEHgAAAAAAAAAAAHEdAAoRUAAAAAAAAAAAAIGQAMEaAAAAAAAAAAAABh8ADREwAAAAAAAAAAAAkYAAIRAAAAAAAAAAAAACEQACEQAAAAAAAAAAAAAhEAAhQAAAAAAAAAAAAAIRAAIRAAAAAAAAAAAAACEQACETAAAAAAAAAAAADhQABRFwAAAAAAAAAAAAYfAAoRUAAAAAAAAAAAAPFgADESAAAAAAAAAAAAMRIAAIGwAAAAAAAAAAAMEcAADhEwAAAAAAAAAACREwAAwRIAAAAAAAAAADQWAAAA8UMAAAAAAAAABRFQAAAFESAAAAAAAAAHgYAAAAAPEaAAAAAAAABhFQAAAADBGHAAAAAAACEZAAAAAADRGFAAAAADYRhwAAAAAAAhEbWgA8JBGHAAAAAAAADUEREREREbcAAAAAAAAAB5EREREfUAAAAAAAAAAAADUpntoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
if(WRITE)_S.write(filename, digit, offset, filesize);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("DirE/wAA///rWoYxbWsIQvOcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGZmZQAAAAMRERIAAAAEERESAAAAAABREgAAAAAAURIAAAAAAFESAAAAAABREgAAAAAAURIAAAAAAFESAAAAAABREgAAAAAAURIAAAAAAFESAAAAAABREgAAAAAAURIAAAAAAFESAAAAAABREgAAAAAAURIAAAAAAFESAAAAAABREgAAAAAAURIAAAAAAFESAAAAAABREgAAAAAAURIAAAAAAFESAAAAAABREgAAAAAAURIAAAAAAFESAAAAAABREgAAAAAAURIAAAAAAFESAAAAAABREgAAAAAAURIAAAAAAFESAAAAAABREgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("GCrE/wAA//+GMX3v85wQhI5z73v73gQhCEKCEHGM61r3vQxjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuaKwAAAAAAAAAAD+EREe8AAAAAAAACgRERERGJAAAAAADzETRvZIER8AAAAAIRHLAAAJURGgAAALgRUAAAAADxGLAAAGEVAAAAAAAMEVAAAIGAAAAAAAAAgTAAAhHAAAAAAAAAURIADRGgAAAAAAAAoR8ADe6QAAAAAAAAkRUAAAAAAAAAAAAAIRYAAAAAAAAAAAAA8RoAAAAAAAAAAAAA4YAAAAAAAAAAAAAKEUAAAAAAAAAAAAAIEZAAAAAAAAAAAABRFQAAAAAAAAAAAAIRgAAAAAAAAAAAAJgRoAAAAAAAAAAAAIEVAAAAAAAAAAAADBGAAAAAAAAAAAAAURiQAAAAAAAAAAAFERIAAAAAAAAAAABREWAAAAAAAAAAAAURFQAAAAAAAAAAAPERUAAAAAAAAAAABREcAAAAAAAAAAAAURFAAAAAAAAAAAAFERQAAAAAAAAAAABREUAAAAAAAAAAAAURFAAAAAAAAAAAAFERwAAAAAAAAAAABRETRERERERERESwCBERERERERERERGQCBERERERERERERGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("GCrE/wAA//+CEH3vDGP73gQhCEL3vfOcec6GMXWt73txjG1rAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK3sAAAAAAAAAAABIEREYQAAAAAAAALURERERGWAAAAAABBETlE/BEVYAAAAAsRHiAAAGgRUgAAAAURQAAAAACRHgAAAEEdAAAAAAAKESAAAKFQAAAAAAAHEdAAABHAAAAAAAAAMcAABohAAAAAAAAAoYAAAAAAAAAAAAAAoYAAAAAAAAAAAAAAEZAAAAAAAAAAAAAEEUAAAAAAAAAAAABlFQAAAAAAAAAAAAtRFAAAAAAAAAAAJ5ER0AAAAAAAAAKFERE0AAAAAAAAAAYRERP2AAAAAAAAAALexREVQAAAAAAAAAAAAHkRHwAAAAAAAAAAAABzEXAAAAAAAAAAAAALMYAAAAAAAAAAAAAA0RcAAAAAAAAAAAAAIR4AAAAAAAAAAAAABRwABncAAAAAAAAACBoACREAAAAAAAAAChgADxFgAAAAAAAAARwABxHQAAAAAAAAQRQAADEyAAAAAAACURYAANEeAAAAAAAMEdAAAAoR4gAAAAaBFQAAAAZRFfsAJ9MRVgAAAABlEREREREYYAAAAAAARRERERpAAAAAAAAAAH/pn3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("GSrE/wAA//95zoIQ73sIQnGM85wEIYpSDGP73hCEkpT3vQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACHd4AAAAAAAAAAAAAHERUAAAAAAAAAAAAKERFQAAAAAAAAAAAIsREVAAAAAAAAAAAAcRIRUAAAAAAAAAAAoRuhFQAAAAAAAAAAixGKEVAAAAAAAAAABxHAoRUAAAAAAAAAChGwChFQAAAAAAAACLEYAKEVAAAAAAAAAHEcAAoRUAAAAAAAAFEbAAChFQAAAAAAADsRgAAKEVAAAAAAAA0RwAAAoRUAAAAAAAgRsAAAChFQAAAAAACxFQAAAFEVAAAAAADBHQAAAAURUAAAAACBGzAAAABRFQAAAAALEZAAAAAFEVAAAAAMEXAAAAAAURUAAAAIEbgAAAAABRFQAAAAIR7MzMyqqsEdqqMACxERERERERERERGAALEREREREREREREYAAiIiIiIiIiKEZiIAAAAAAAAAAAAURUAAAAAAAAAAAAABRFQAAAAAAAAAAAAAFEVAAAAAAAAAAAAAAURUAAAAAAAAAAAAABRFQAAAAAAAAAAAAAFEVAAAAAAAAAAAAAAURUAAAAAAAAAAAAABRFQAAAAAAAAAAAAAFEVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("GSrE/wAA//9974IQ85xtawhC73sEIfve9715zoYxDGNxjHWtAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAORERERERERFAAAAAAERERERERERoAAAAAYRERERERERGgAAAABRHAAAAAAAAAAAAAAEEQAAAAAAAAAAAAAAsbAAAAAAAAAAAAAAARQAAAAAAAAAAAAABhFQAAAAAAAAAAAAAFEWAAAAAAAAAAAAAAQRAAAAAAAAAAAAAACxsAAAAAAAAAAAAAAxHwAAAAAAAAAAAAAGEXiIgAAAAAAAAAAAURERERK+YAAAAAAADxEREREREbgAAAAAANd3d3d0oREXAAAAAAAAAAAAAIQRFwAAAAAAAAAAAAAMkRUAAAAAAAAAAAAADCEjAAAAAAAAAAAAAAcRcAAAAAAAAAAAAAAyGQAAAAAAAAAAAAAA4RgAAAAAAAAAAAAADRFgA2YwAAAAAAAAAGEWANEWAAAAAAAAAAYRYAYR0AAAAAAAAABRHAAxHwAAAAAAAAAKEgAAoSgAAAAAAAAIEUAABhHwAAAAAAAAkRYAAAoRcAAAAAAAcRQAAACCEegAAAAD8RmAAAAAwhGXwANnIRmAAAAAAIkRERERERqAAAAAAAANkREREb0AAAAAAAAAAGXk5WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("GirE/wAA//+KUn3v85wMY4IQcYwEIfve970IQu97hjHrWo5zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACRCAAAAAAAAAAAAAAiROAAAAAAAAAAAAAAMEcAAAAAAAAAAAAAAgRkAAAAAAAAAAAAAAEEVAAAAAAAAAAAAAAIRoAAAAAAAAAAAAAAJEYAAAAAAAAAAAAAAURQAAAAAAAAAAAAACJGYAAAAAAAAAAAAAAQR8AAAAAAAAAAAAACBGQAAAAAAAAAAAAAAQRUG24AAAAAAAAAABRGnkRETpQAAAAAAAAkRERERERGYAAAAAADxERrC2yeREcAAAAAIkRkgAAAADzEcAAAABBGYAAAAAACJESAAAIEZgAAAAAAACDE2AABBEgAAAAAAAADxHAAIEaAAAAAAAAAAAxkAAhFQAAAAAAAAAAcRgAwR0AAAAAAAAAACEVAEEQAAAAAAAAAACBFQBBEAAAAAAAAAAA0RUAcRYAAAAAAAAAALESAFEbAAAAAAAAAADBHQBhFAAAAAAAAAAAkZAAChGAAAAAAAAABRFAAAsRkAAAAAAAAIkRgAAAoRQAAAAAAAaRHAAAAGkRmAAAAAC5EaAAAAAIkRFLYAgqERpgAAAAAIQRERERERFwAAAAAAAAWhERERGtAAAAAAAAAACFdExWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("GyrE/wAA//+GMYIQfe/znI5zDGN1rQQh+95xjO97EIQIQutaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1VVVVVVVVVVVVVVXgCRERERERERERERERFwCRERERERERERERERFwAAAAAAAAAAAAAAOhSQAAAAAAAAAAAAAA0R0AAAAAAAAAAAAAAJEaAAAAAAAAAAAAAAAFEXAAAAAAAAAAAAAADhGAAAAAAAAAAAAAAAChGQAAAAAAAAAAAAAAcRUAAAAAAAAAAAAAAJoakAAAAAAAAAAAAAALEWAAAAAAAAAAAAAACRGgAAAAAAAAAAAAAABRFwAAAAAAAAAAAAAAcRUAAAAAAAAAAAAAAAoRkAAAAAAAAAAAAAAHEdAAAAAAAAAAAAAACaGpAAAAAAAAAAAAAABRFwAAAAAAAAAAAAAAkRoAAAAAAAAAAAAAAAgRIAAAAAAAAAAAAAAHEVAAAAAAAAAAAAAAAKEZAAAAAAAAAAAAAADRHQAAAAAAAAAAAAAAlBoAAAAAAAAAAAAAAAURcAAAAAAAAAAAAAAJEaAAAAAAAAAAAAAAAKEZAAAAAAAAAAAAAABxFQAAAAAAAAAAAAAAChqQAAAAAAAAAAAAAA0RYAAAAAAAAAAAAAAJEaAAAAAAAAAAAAAAAFEXAAAAAAAAAAAAAAAhFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("GCrE/wAA//+CEHGMfe/znPveBCEIQve9DGNta+97da2GMetaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4ggAAAAAAAAAACJQREWVwAAAAAAAHkREREREcAAAAAADmERm6o2ER0gAAAAdhGXAAAAphFQAAAA0RUAAAAAB2EaAAAIEWAAAAAAAIEWAAAFEaAAAAAAAAkRgAAJEQAAAAAAAAoRsAAGFgAAAAAAAAgRwAAGFAAAAAAAAAgRwAANEeAAAAAAAAMR8AALETAAAAAAACYRIAACYRgAAAAAADEVAAAAgRSgAAAAIxFnAAAADBEVgAArYRZwAAAAAKYREWQREZcAAAAAAAMRERERFOAAAAAAB2ERRllhERMAAAAAdhFqIAAHwRHQAAAHYRMgAAAAB2ETAAAFETAAAAAAAHYRgABxFiAAAAAAAAgRkAChGgAAAAAAAACREgDRHgAAAAAAAAAxHwCREAAAAAAAAAChGgCREgAAAAAAAACxGgBRGAAAAAAAAABRGAChEwAAAAAAAABhEgAkFHAAAAAAAAwRUAAMEWcAAAAAAIERcAAAYRZwAAAACxEcAAAAdhEVggB7kRHAAAAAB1EREREREUsAAAAAAAqRERERRXAAAAAAAAAHo1XPIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
digit = atob("GSrE/wAA//9974IQcYzznPveBCEIQve9DGPvexCEec5ta45zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4gwAAAAAAAAAAAKkhERZXAAAAAAAACGERERERFTAAAAAADBESX6rJERZwAAAADBEsMAAAB2EWcAAACBFnAAAAAADBGQAAAGEXAAAAAAAAQR8AAKEcAAAAAAAAA2EjAAkWAAAAAAAAAA8RgAARUAAAAAAAAAAxFABxGgAAAAAAAAAA0ZAIEYAAAAAAAAAACRYAgRgAAAAAAAAAAJHQBxHwAAAAAAAAAA0ZAAIZAAAAAAAAAAcRQABRIwAAAAAAAABRFwAIEUAAAAAAAABxFQAACRHAAAAAAAA2EXAAADYRwAAAAAB2EVAAAAB2EWgAAAPCERcAAAAAdhESmV0RERwAAAAAAAphERERIRYAAAAAAAAAj0VfjBGgAAAAAAAAAAAABxFgAAAAAAAAAAAAAFEXAAAAAAAAAAAAAKEVAAAAAAAAAAAAAAYScAAAAAAAAAAAAA8RwAAAAAAAAAAAAAdhYAAAAAAAAAAAAABRGgAAAAAAAAAAAABxHQAAAAAAAAAAAAAJEXAAAAAAAAAAAAAKEVAAAAAAAAAAAAAAYScAAAAAAAAAAAAAwRwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
if(WRITE)_S.write(filename, digit, offset);
print(`_S.read('${filename}', ${offset}, ${digit.length}); //${cnt++}`);
offstr += `${offset}, `;lenstr += `${digit.length}, `;offset += digit.length;
print(`Filesize: ${offset}`);
print(`Offsets: [${offstr}]`);
print(`Lengths: [${lenstr}]`);
/*
function getDigit(d) {
  return(_S.read("Urbanist54",
  [0, 645, 975, 1515, 2055, 2616, 3177, 3759, 4362, 4902, ][d],
  [645, 330, 540, 540, 561, 561, 582, 603, 540, 561, ][d]));
}
*/